Update вв

diff --git a/вв b/вв
--- a/вв
+++ b/вв
@@ -1,38 +1,42 @@
-Big5Freq.tab	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-CharDistribution.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-EUCKRFreq.tab	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-EUCTWFreq.tab	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-GB2312Freq.tab	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-JISFreq.tab	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-JpCntx.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-blake2s.hpp	public-domain	LicenseRef-scancode-public-domain		
-blake2sp.cpp	cc0-1.0	CC0-1.0		
-cityhash.H	mit	MIT	Copyright (c) 2011 Google, Inc.	Google, Inc.
-ioapi.h			Copyright (c) 1998-2010 Gilles Vollant (minizip) ( http://www.winimage.com/zLibDll/minizip.html ) | Copyright (c) 2009-2010 Mathias Svensson ( http://result42.com )	Gilles Vollant | Mathias Svensson
-json.hpp	mit AND apache-2.0	MIT AND Apache-2.0	Copyright (c) 2008-2009 Bjoern Hoehrmann <bjoern@hoehrmann.de> @sa http://bjoern.hoehrmann.de/utf-8/decoder/dfa | Copyright (c) 2009 Florian Loitsch | Copyright 2008-2009 Bjorn Hoehrmann <bjoern@hoehrmann.de> | Copyright 2009 Florian Loitsch https://florian.loitsch.com | Copyright 2013-2023 Niels Lohmann https://nlohmann.me | Copyright 2016-2021 Evan Nemerson <evan@nemerson.com> | Copyright 2018 The Abseil Authors | copyright (c) 2013-2023 Niels Lohmann	Bjoern Hoehrmann @sa | Bjorn Hoehrmann | Evan Nemerson | Florian Loitsch | Niels Lohmann | The Abseil Authors
-loclang.hpp			Copyright (c) 1993- d Alexander Roshal	d Alexander Roshal
-mongoose.h	((gpl-2.0 OR commercial-license) AND (gpl-2.0 OR unknown-spdx)) AND public-domain AND bsd-simplified AND (bsd-simplified AND cc0-1.0)	((GPL-2.0-only OR LicenseRef-scancode-commercial-license) AND (GPL-2.0-only OR LicenseRef-scancode-unknown-spdx)) AND LicenseRef-scancode-public-domain AND BSD-2-Clause AND (BSD-2-Clause AND CC0-1.0)	Copyright (c) 2004-2013 Sergey Lyubka | Copyright (c) 2013-2025 Cesanta Software Limited | Copyright (c) 2023 Cesanta Software Limited | Copyright 2014, Kenneth MacKay | Copyright 2015, Kenneth MacKay	Cesanta Software Limited | Kenneth MacKay | Sergey Lyubka
-nsBig5Prober.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsCharSetProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 2001 the Initial Developer	the Initial Developer
-nsCodingStateMachine.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsEUCJPProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsEUCKRProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsEUCTWProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsEscCharsetProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsGB2312Prober.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsHebrewProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 2005 the Initial Developer	the Initial Developer
-nsLatin1Prober.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 2001 the Initial Developer	the Initial Developer
-nsMBCSGroupProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsPkgInt.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsSBCSGroupProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 2001 the Initial Developer	the Initial Developer
-nsSBCharSetProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 2001 the Initial Developer	the Initial Developer
-nsSJISProber.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsUTF8Prober.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-nsUniversalDetector.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998 the Initial Developer	the Initial Developer
-obsolete/protypes.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998-2000 the Initial Developer	the Initial Developer
-prcpucfg.h	bsd-new	BSD-3-Clause	Copyright 2008, Google Inc.	Google Inc.
-prcpucfg_linux.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998-2000 the Initial Developer	the Initial Developer
-prmem.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998-2000 the Initial Developer	the Initial Developer
-prtypes.h	mpl-1.1 OR gpl-2.0-plus OR lgpl-2.1-plus	MPL-1.1 OR GPL-2.0-or-later OR LGPL-2.1-or-later	Portions created by the Initial Developer are Copyright (c) 1998-2000 the Initial Developer	the Initial Developer
-unzip.h	zlib	Zlib	Copyright (c) 1998-2010 Gilles Vollant (minizip) ( http://www.winimage.com/zLibDll/minizip.html ) | Copyright (c) 2007-2008 Even Rouault | Copyright (c) 2009-2010 Mathias Svensson ( http://result42.com )	Even Rouault | Gilles Vollant | Mathias Svensson
-zip.h	zlib	Zlib	Copyright (c) 1998-2010 Gilles Vollant (minizip) ( http://www.winimage.com/zLibDll/minizip.html ) | Copyright (c) 2009-2010 Mathias Svensson ( http://result42.com )	Gilles Vollant | Mathias Svensson
+#!/usr/bin/env bash
+set -euo pipefail
+
+DEST="${1:-./sources}"
+mkdir -p "$DEST"
+
+GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
+ok=0; skip=0; fail=0
+
+clone() {
+    local name="$1" url="$2"
+    local dir="$DEST/$name"
+    if [ -d "$dir/.git" ]; then
+        echo -e "${YELLOW}[SKIP]${NC} $name — already cloned"
+        ((skip++)) || true
+    else
+        echo -e "${GREEN}[GIT ]${NC} $name  <- $url"
+        if git clone --depth=1 "$url" "$dir" 2>/dev/null; then
+            ((ok++)) || true
+        else
+            echo -e "${RED}[FAIL]${NC} $name"
+            ((fail++)) || true
+        fi
+    fi
+}
+
+clone "uchardet"     "https://github.com/BYVoid/uchardet.git"
+clone "nspr"         "https://github.com/mozilla/nspr.git"
+clone "cityhash"     "https://github.com/google/cityhash.git"
+clone "zlib-minizip" "https://github.com/madler/zlib.git"
+clone "mongoose"     "https://github.com/cesanta/mongoose.git"
+clone "nlohmann-json" "https://github.com/nlohmann/json.git"
+clone "blake2"       "https://github.com/BLAKE2/BLAKE2.git"
+clone "unrar"        "https://github.com/aawc/unrar.git"
+
+echo ""
+echo -e "Done: ${GREEN}ok=$ok${NC}  ${YELLOW}skip=$skip${NC}  ${RED}fail=$fail${NC}"
+echo "Output: $DEST"
+echo ""
+echo "NOTE: unrar — официальный RARLAB закрыт, использован форк aawc/unrar."
+echo "      Оригинал: https://www.rarlab.com/rar_add.htm"
+echo "      minizip лежит в contrib/minizip/ внутри zlib-minizip/"
